name: Test Linter

on:
  push:
    branches:
      - "**"
      - "!prod"
  pull_request:
    types: [opened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          node-version: 18
      - run: yarn install
      - run: yarn lint
